# Generated by Django 5.1 on 2024-08-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='img',
            field=models.ImageField(null=True, upload_to='Imagens/'),
        ),
    ]
