# Generated by Django 5.1 on 2024-08-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_dados_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='img',
            field=models.ImageField(null=True, upload_to='./Imagens/'),
        ),
    ]
