# Generated by Django 5.1 on 2024-08-27 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_alter_dados_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dados',
            name='cpf',
        ),
    ]
